name: Build and test

on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version-file: genhash/go.mod
          cache-dependency-path: genhash/go.sum

      - name: Build Genhash
        working-directory: ./genhash
        run: make

      - name: Setup Node.js environment
        uses: actions/setup-node@v3.5.0
        with:
          cache-dependency-path: genhash/package-lock.json

      - name: Install Node Packages
        working-directory: ./genhash
        run: npm i

      # - name: Cache unhashed safelist
      #   id: cache-unhashed
      #   uses: actions/cache@v2
      #   with:
      #     path: genhash/safelist-unhashed.json
      #     key: ${{ runner.os }}-unhashed

      # - name: Unhash safelist
      #   working-directory: ./genhash
      #   if: steps.cache-unhashed.outputs.cache-hit != 'true'
      #   run: node unhash-safelist.js

      # - name: Cache generated safelist
      #   id: cache-generated
      #   uses: actions/cache@v2
      #   with:
      #     path: genhash/generated-hashes.json
      #     key: ${{ runner.os }}-generated

      # - name: Generate hashed safelist
      #   working-directory: ./genhash
      #   if: steps.cache-generated.outputs.cache-hit != 'true'
      #   run: ./genhash safelist-unhashed.json generated-hashes.json

      - name: Test
        working-directory: ./genhash
        run: |
          echo 'Unhashing Safelist...'
          node unhash-safelist.js
          echo 'Generating hashes...'
          ./genhash safelist-unhashed.json safelist-generated.json
          npm run test
